PORTFOLIO_PAYLOAD = {
    "profile": {
        "name": "Ishika",
        "title": "Full Stack Software Engineering Student",
        "location": "Mohali, Punjab",
        "email": "soniishika081@gmail.com",
        "links": {
            "github": "https://github.com/ishikasoni2005",
            "linkedin": "https://www.linkedin.com/in/ishikasoni2005/",
            "leetcode": "https://leetcode.com/u/ishikasoni2025/",
        },
    },
    "projects": [
        {
            "title": "DevCompass",
            "category": "AI",
            "description": "An AI-powered platform that analyzes developer skills and learning progress to generate personalized roadmaps, project ideas, and interview preparation guidance.",
            "tech": ["Python", "FastAPI", "OpenAI API", "LLM Workflows"],
            "github": "https://github.com/ishikasoni2005/DevCompass",
            "live": None,
        },
        {
            "title": "SecureX",
            "category": "AI",
            "description": "An AI-powered web application that detects scam and phishing messages in real time with NLP models, confidence scores, and a privacy-friendly workflow.",
            "tech": ["React", "Django REST", "NLP", "Machine Learning"],
            "github": "https://github.com/ishikasoni2005/SecureX",
            "live": None,
        },
        {
            "title": "CollabCast",
            "category": "Full Stack",
            "description": "A real-time collaboration platform that lets creators join rooms, communicate through live audio and video, chat instantly, and manage shared podcast sessions.",
            "tech": ["React", "Django", "WebRTC", "WebSockets"],
            "github": "https://github.com/ishikasoni2005/CollabCast",
            "live": "https://collab-cast-two.vercel.app",
        },
        {
            "title": "SEO Analyzer",
            "category": "Analytics",
            "description": "An intelligent SEO analysis tool that evaluates content quality, readability, and keyword usage to suggest better search visibility improvements.",
            "tech": ["React", "Django", "spaCy", "TextRazor"],
            "github": "https://github.com/ishikasoni2005/Seo-Analyzer",
            "live": None,
        },
        {
            "title": "Student Performance Prediction Dashboard",
            "category": "Analytics",
            "description": "A Streamlit dashboard that analyzes academic performance patterns and predicts GPA trends using interactive visualizations and machine learning.",
            "tech": ["Python", "Streamlit", "Pandas", "Linear Regression"],
            "github": "https://github.com/ishikasoni2005/Student_Performance_Prediction_Dashboard",
            "live": None,
        },
        {
            "title": "TSP Project",
            "category": "Algorithms",
            "description": "A visual solver for the Travelling Salesman Problem that compares brute force, dynamic programming, genetic algorithm, and simulated annealing strategies.",
            "tech": ["JavaScript", "Canvas", "Algorithms", "Visualization"],
            "github": "https://github.com/ishikasoni2005/TSP-Project",
            "live": None,
        },
        {
            "title": "IPO Web Application",
            "category": "Full Stack",
            "description": "A full stack IPO tracking application that helps users explore upcoming, ongoing, and listed IPOs through a responsive dashboard powered by React and Django REST Framework.",
            "tech": ["React", "Django REST Framework", "Python", "MySQL"],
            "github": "https://github.com/ishikasoni2005/IPO-Web-Application-REST-API-Development",
            "live": None,
        },
        {
            "title": "Intro",
            "category": "Full Stack",
            "description": "A real-time collaboration platform for developers to discover teammates, discuss ideas, and build projects together using live communication features.",
            "tech": ["React", "Django", "WebSockets", "WebRTC"],
            "github": "https://github.com/ishikasoni2005/Intro",
            "live": None,
        },
        {
            "title": "Accessible Roll Chair",
            "category": "Hardware",
            "description": "An Arduino-based smart wheelchair for visually impaired users that detects obstacles, alerts through a buzzer, and automatically stops the motors for safer mobility.",
            "tech": ["Arduino", "C++", "Ultrasonic Sensor", "Motor Control"],
            "github": "https://github.com/ishikasoni2005/Accessible-Roll-Chair",
            "live": None,
        },
        {
            "title": "Automatic Hand Sanitizer",
            "category": "Hardware",
            "description": "An Arduino-based touchless sanitizer system that uses an IR sensor and servo motor to automate dispensing in public spaces, classrooms, and workplaces.",
            "tech": ["Arduino", "C++", "IR Sensor", "Servo Motor"],
            "github": "https://github.com/ishikasoni2005/Automatic-Hand-Sanitizer",
            "live": None,
        },
        {
            "title": "Ishika Portfolio",
            "category": "Frontend",
            "description": "A responsive portfolio website that presents projects, skills, experience, and public profiles through a polished interface built for recruiters and collaborators.",
            "tech": ["React", "Vite", "TailwindCSS", "Framer Motion"],
            "github": "https://github.com/ishikasoni2005/Ishika-Portfolio",
            "live": None,
        },
    ],
}
